# configs/switch_quick/mlp/mcts.yaml
# -------------------------------------------------
# DATA SET
dataset: "switch15to6"          # the name you registered in data.py
data_path: data               # root folder:  <project>/data/Switch15to6/
channels: 15                  # input length
num_classes: 6
input_mode: vec               # vector, not image

# SEARCH
search_space: "mlp"             # grammar file: configs/grammars/mlp.yaml
search_strategy: "mcts"
steps: 20                    # total MCTS iterations
seed: 0                       # random seed

# TRAINING
score: "multi_hot"
batch_size: 512
lr: 0.01
epochs: 4                     # epochs per candidate
weight_decay: 0.0001

patience: 8
test_epochs: 64
hpo_runs: 1
momentum: 0.9

# RESOURCE LIMITS
device: cuda:0
individual_mem_limit: 512     # MB per model
mem_limit: 4096               # total GPU memory watchdog
time_limit: 600               # seconds; 0 means no limit
depth_limit: 20               # max DSL recursion depth

# LOGGING & PLOTS
verbose_search: false
verbose_eval:   false
visualise:      true          # show derivation tree windows
vis_interval:   20            # draw every 20 iterations
visualise_scale: 0.8
print_after:    100           # console summary interval

# saving results and figures
figures_path: "figures"
results_path: "results"

# continue search
continue_search: true
